INSERT INTO HUESPED (NOMBRE,DNI,EDAD,EMAIL) VALUES('',0,0,'');
INSERT INTO HUESPED (NOMBRE,DNI,EDAD,EMAIL) VALUES('',0,0,'');
INSERT INTO HUESPED (NOMBRE,DNI,EDAD,EMAIL) VALUES('',0,0,'');
INSERT INTO HUESPED (NOMBRE,DNI,EDAD,EMAIL) VALUES('',0,0,'');

INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (0,0,0,0);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (0,0,0,0);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (0,0,0,0);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (0,0,0,0);

INSERT INTO RESERVA(NUMERO,DNI,TIEMPO) VALUES (0,0,'');
INSERT INTO RESERVA(NUMERO,DNI,TIEMPO) VALUES (0,0,'');
INSERT INTO RESERVA(NUMERO,DNI,TIEMPO) VALUES (0,0,'');
