-- INSERT INTO HUESPED (NOMBRE,DNI,EDAD,EMAIL) VALUES('',0,0,'');
-- INSERT INTO HUESPED (NOMBRE,DNI,EDAD,EMAIL) VALUES('',0,0,'');
-- INSERT INTO HUESPED (NOMBRE,DNI,EDAD,EMAIL) VALUES('',0,0,'');

INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (101,1,100,1);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (102,1,150,2);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (103,1,200,3);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (104,1,250,4);

INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (201,2,400,1);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (202,2,450,2);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (203,2,500,3);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (204,2,550,4);

INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (301,3,700,1);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (302,3,750,2);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (303,3,800,3);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (304,3,850,4);

INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (401,4,1000,1);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (402,4,1500,2);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (403,4,1100,3);
INSERT INTO HABITACION(NUMERO,PISO,PREXNOC,CANTPERS) VALUES (404,4,1150,4);

-- INSERT INTO RESERVA(NUMERO,DNI,TIEMPO) VALUES (0,0,'');
-- INSERT INTO RESERVA(NUMERO,DNI,TIEMPO) VALUES (0,0,'');
-- INSERT INTO RESERVA(NUMERO,DNI,TIEMPO) VALUES (0,0,'');

INSERT INTO USUARIOS(USER,PASSWORD) VALUES ('Lucio','ola');
INSERT INTO USUARIOS(USER,PASSWORD) VALUES ('Urquiza','ola');
